name: video_player
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_vlc: ^0.4.0

  storage_api:
    path: D://custom_dart_libraries//storage_api
  
  local_storage_api:
    path: D://custom_dart_libraries//local_storage_api
    
  flutter_bloc: ^8.1.1
  meta: ^1.8.0
  bloc: ^8.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  google_fonts: ^3.0.1
  file_picker: ^5.2.4
  path: ^1.8.2
  synchronized: ^3.0.0+3
  ffmpeg_kit_flutter: ^5.1.0
  process_run: ^0.12.5
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
